require File.dirname(__FILE__) + "/test/extensions/test_result"
require File.dirname(__FILE__) + "/test/extensions/error"
require File.dirname(__FILE__) + "/test/runner"
require File.dirname(__FILE__) + "/test/supervised_test_suite"
require File.dirname(__FILE__) + "/test/work_unit"
